### ISSUE TITLE
Floor labels are disappearing

### ISSUE THREAD

**Issue by ce-bo** [MaibornWolff/codecharta#3137]
# Bug

## Expected Behavior

<GIVEN>

WHEN
viewing a map

THEN
the floor labels should be visible all the time.

## Actual Behavior
the floor labels are partially or fully hidden.

## Screenshots
![image](https://user-images.githubusercontent.com/26900540/202646975-ddfcf967-ea0a-4209-8fad-6b8041fcabfd.png)

## Specifications
- is released in [online-demo](https://maibornwolff.github.io/codecharta/visualization/app/index.html?file=codecharta.cc.json.gz&file=codecharta_analysis.cc.json.gz): yes | no
- CodeCharta Version: 1.111.0
- OS: all
- Browser: all

## Development Notes
- When scaling up the height (height metric options) they are appearing again.
- It seems that they are on the same height as the floor planes, so that z-buffer fighting takes place.
- One idea would be to set the floor labels per default a bit higher. I think this was the case some time ago, but it has changed.

**Comment by MW-Friedrich** [comment]
This might have been fixed by #3077 maybe. At least on my machine the flickering of the floor lables has gotten much better 👀

**Comment by ChristianHuehn** [comment]
Better maybe but still broken, had the problem when trying to create a screenshot from eagle vision. Took me solid 2 minutes to find the perfect angle to see most labels

**Comment by ViktoriaGordeevaVG** [comment]
This issue is closely related to issue #2770. In the current version, the decimal places do not matter at all. Although they can be set, only the integer values are accepted when adjusting the height. This doesn't appear to be a significant issue at the moment, so the #2770 issue is being closed.

Regarding issue #3137, the disappearance of folder labels does not seem to be a major problem either. Even with large maps, such as NetBeans [https://maibornwolff.github.io/codecharta/showcase/netbeans/], it seems to work correctly. The assumption is that this issue may have been partially resolved with the update of Three.js, or the disappearing problems could likely be caused by the PCs themselves, as loading large maps consumes around 15 GB of RAM.

**Comment by phanlezz** [comment]
@ChristianHuehn try to recreate the issue with our updates to three.js. If you are able to recreate this issue, try to produce a set of steps to recreate this issue on other machines. Also monitor your HW resource allocation, as it may just be an out of RAM situation.

**Comment by ChristianHuehn** [comment]
Nvm I checked it after the release and it was good now. If it comes up again we will create a new issue 👍

**Comment by phanlezz** [comment]
There is more investigation required. 
The problem's appearance is independent of the quality settings, but it changes its behavior a little bit.

**Comment by phanlezz** [comment]
Example Map: 
[netbeans_2018-10-19.cc.zip](https://github.com/user-attachments/files/17127223/netbeans_2018-10-19.cc.zip)
(source: [Github Pages Showcase](https://maibornwolff.github.io/codecharta/showcase/netbeans/))
With rloc mcc mcc

**Comment by phanlezz** [comment]
I seems the problem has something to do with the amount of floor labels presented. 
![grafik](https://github.com/user-attachments/assets/6e62d58f-063b-425f-b68c-1fa51f93a3ba)
I'm not able to reproduce the disappearing of floor labels when there are only a few labels present.

**Comment by phanlezz** [comment]
If I adjust the amount of labels manually down, so that only the first two levels (instead of 3) of hierarchy (instead of 3) are shown, the problem does not occur. 
![grafik](https://github.com/user-attachments/assets/7932f9f5-33c4-4854-90fa-69a4715c9d03)

**Comment by phanlezz** [comment]
Some early speculation:
There seems to be a correlation between the font size and the flickering. If the map is large enough and there are many folders on hierarchy levels 1 and 2  (which in turn increases the map size even more) the displayed text gets so small in a relative sense to the display that it gets de-rendered. 
The problem seems to be intertwined with the map generation algorithm, which makes it hard to debug.

**Comment by phanlezz** [comment]
With a grain of salt: 
`mapWidth > scalingThreshold ? scalingThreshold / mapWidth : 1` 
If the statement above in (floorLabelHelper.ts) returns a value non-equal to 1 the flickering seems to appear.

**Comment by phanlezz** [comment]
I suspect that the theory from @ChristianHuehn might have some truth to it. Iirc he suggested, that we do something wrong in the calculation of the label or folder height. 
But it is not **_what we are doing_** to the height of labels etc. it's what we **_don't do_**. 
On giant maps, the height of folders etc. does not scale (or does not scale enough) with the size of the map. A 100u big map has folder height 2, same as a map of size 30ku. If such a large map gets then rendered so small as it needed, the different layers of the folder structure clip through each other and through the labels.

I suspect that, because if the height factor in the height metric settings is raised, the clipping gets reduced. 
If this is true, this issue can be resolved, as it is not directly dependent on the problems with layout algorithm.

**Comment by phanlezz** [comment]
Small update: The problem is not only the "missing" height between folders and labels, but also the height differences of the transparent planes that contain the labels. If those transparent planes are too close to each other in height, they start to clip each other while zoomed out.
